// src/components/section-header.vue
<template>
  <div class = "section-header">
    <h1>{{props.title}}</h1>
  </div>
</template>

<script setup>
const props = defineProps({
  title: String
});
</script>

<style lang="scss" scoped>
.section-header{
    position: relative;
    width: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 20px;
}
</style>

// src/ui/landing/section-header.tsx
import React, {FC} from "react";

interface Props {
    title: string
}

export const SectionHeader: FC<Props> = ({title}) => { {
    return (
        <div className="w-full flex flex-col h-30 justify-center items-center text-center">
            <div className={"relative"}><h2>{title}</h2></div>
        </div>
    );
}}
